### ISSUE TITLE
Branch `temp`

### ISSUE THREAD

**Issue by andrejbauer** [Migelo/SpaceMe#4]
Ime veje `temp` je strašansko neinformativno. Kaj počneta na tej veji? Naslednjič izberita primerno ime za vejo.

**Comment by Migelo** [comment]
Noter piševa testni primer uporabniškega vmesnika. Bova ustrezno poimenovala.

**Comment by andrejbauer** [comment]
Ma ni treba zdaj komplicirat, naslednjič pametno poimenujta branch, ko ga bosta imela.

**Comment by andrejbauer** [comment]
Gremo spat!

**Comment by Migelo** [comment]
Zmenjeno in lahko noč.
